Repository kiserd/OSU-CS467-Capstone-Project, pull requests merged in 2021-11, with the labels that each got.

#56 Enhancement Cleanup For Hosting/Deploy
  portfolio-project-matching-app/.firebase/hosting.b3V0.cache
  portfolio-project-matching-app/.firebaserc
  portfolio-project-matching-app/components/DBForm.js
  portfolio-project-matching-app/components/DBList.js
  portfolio-project-matching-app/components/DBListItem.js
  portfolio-project-matching-app/components/UserIcon.js
  portfolio-project-matching-app/firebase.json
  portfolio-project-matching-app/next.config.js
  portfolio-project-matching-app/package.json
  portfolio-project-matching-app/pages/index.js
  portfolio-project-matching-app/pages/sillyPage.js
  portfolio-project-matching-app/pages/test_Nav.js
  portfolio-project-matching-app/pages/test_daoPage.js
  portfolio-project-matching-app/pages/test_filterButtonsPage.js
  portfolio-project-matching-app/pages/test_inputDropdownPage.js
  portfolio-project-matching-app/pages/test_loginPage.js
  portfolio-project-matching-app/pages/test_projectCardPage.js
  portfolio-project-matching-app/pages/test_searchPage.js
  portfolio-project-matching-app/pages/test_textareaPage.js
  portfolio-project-matching-app/public/favicon.ico
  portfolio-project-matching-app/public/vercel.svg
Labels: enhancement

#58 Sprint-3 Merge to Main
  portfolio-project-matching-app/.firebase/hosting.b3V0.cache
  portfolio-project-matching-app/.firebaserc
  portfolio-project-matching-app/backend/dao.js
  portfolio-project-matching-app/components/DBForm.js
  portfolio-project-matching-app/components/DBList.js
  portfolio-project-matching-app/components/DBListItem.js
  portfolio-project-matching-app/components/FilterButtons.js
  portfolio-project-matching-app/components/MultipleInputDropdown.js
  portfolio-project-matching-app/components/Nav.js
  portfolio-project-matching-app/components/ProfileForm.js
  portfolio-project-matching-app/components/ProjectCard.js
  portfolio-project-matching-app/components/UserIcon.js
  portfolio-project-matching-app/firebase.json
  portfolio-project-matching-app/models/Project.js
  portfolio-project-matching-app/next.config.js
  portfolio-project-matching-app/package-lock.json
  portfolio-project-matching-app/package.json
  portfolio-project-matching-app/pages/browseProjects.js
  portfolio-project-matching-app/pages/index.js
  portfolio-project-matching-app/pages/newProject.js
  portfolio-project-matching-app/pages/project.js
  portfolio-project-matching-app/pages/sillyPage.js
  portfolio-project-matching-app/pages/test_Nav.js
  portfolio-project-matching-app/pages/test_daoPage.js
  portfolio-project-matching-app/pages/test_filterButtonsPage.js
  portfolio-project-matching-app/pages/test_inputDropdownPage.js
  portfolio-project-matching-app/pages/test_loginPage.js
  portfolio-project-matching-app/pages/test_projectCardPage.js
  portfolio-project-matching-app/pages/test_searchPage.js
  portfolio-project-matching-app/pages/test_textareaPage.js
  portfolio-project-matching-app/public/favicon.ico
  portfolio-project-matching-app/public/vercel.svg
Labels: enhancement

#59 Enhancement browse filtering
  portfolio-project-matching-app/components/FilterButtons.js
  portfolio-project-matching-app/models/FilteredProject.js
  portfolio-project-matching-app/pages/browseProjects.js
Labels: enhancement

#62 Enhancement dao CUD
  portfolio-project-matching-app/Firebase/clientApp.ts
  portfolio-project-matching-app/backend/dao.js
  portfolio-project-matching-app/backend/daoProject.js
  portfolio-project-matching-app/backend/daoTechnology.js
  portfolio-project-matching-app/backend/daoUser.js
  portfolio-project-matching-app/models/Project.js
  portfolio-project-matching-app/models/Technology.js
  portfolio-project-matching-app/models/User.js
  portfolio-project-matching-app/pages/test_dao.js
Labels: enhancement

#63 Auth
  portfolio-project-matching-app/Firebase/auth.js
  portfolio-project-matching-app/components/NewLogin.js
  portfolio-project-matching-app/components/ProfileForm.js
  portfolio-project-matching-app/context/AuthContext.js
  portfolio-project-matching-app/pages/_app.js
  portfolio-project-matching-app/pages/signIn.js
Labels: enhancement

#64 Search Projects
  portfolio-project-matching-app/pages/browseProjects.js
Labels: enhancement

#65 Enhancement browse filter search orchestration
  portfolio-project-matching-app/models/FilteredProject.js
  portfolio-project-matching-app/models/Project.js
  portfolio-project-matching-app/pages/browseProjects.js
Labels: enhancement

#67 Enhancement testing
  portfolio-project-matching-app/__mocks__/fileMock.js
  portfolio-project-matching-app/__mocks__/styleMock.js
  portfolio-project-matching-app/__tests__/dummy.test.js
  portfolio-project-matching-app/jest.config.js
  portfolio-project-matching-app/package-lock.json
  portfolio-project-matching-app/package.json
  portfolio-project-matching-app/pages/test_dao.js
Labels: enhancement

#68 Sprint 4
  portfolio-project-matching-app/Firebase/auth.js
  portfolio-project-matching-app/Firebase/clientApp.ts
  portfolio-project-matching-app/__mocks__/fileMock.js
  portfolio-project-matching-app/__mocks__/styleMock.js
  portfolio-project-matching-app/__tests__/dummy.test.js
  portfolio-project-matching-app/backend/dao.js
  portfolio-project-matching-app/backend/daoProject.js
  portfolio-project-matching-app/backend/daoTechnology.js
  portfolio-project-matching-app/backend/daoUser.js
  portfolio-project-matching-app/components/FilterButtons.js
  portfolio-project-matching-app/components/Nav.js
  portfolio-project-matching-app/components/NewLogin.js
  portfolio-project-matching-app/components/ProfileForm.js
  portfolio-project-matching-app/context/AuthContext.js
  portfolio-project-matching-app/jest.config.js
  portfolio-project-matching-app/models/FilteredProject.js
  portfolio-project-matching-app/models/Project.js
  portfolio-project-matching-app/models/Technology.js
  portfolio-project-matching-app/models/User.js
  portfolio-project-matching-app/package-lock.json
  portfolio-project-matching-app/package.json
  portfolio-project-matching-app/pages/_app.js
  portfolio-project-matching-app/pages/browseProjects.js
  portfolio-project-matching-app/pages/signIn.js
  portfolio-project-matching-app/pages/test_dao.js
Labels: enhancement

#69 Enhancement `browseProjects` page `ProjectCard` content reduction
  portfolio-project-matching-app/backend/dao.js
  portfolio-project-matching-app/components/ProjectCard.js
  portfolio-project-matching-app/package-lock.json
  portfolio-project-matching-app/package.json
  portfolio-project-matching-app/pages/browseProjects.js
  portfolio-project-matching-app/pages/test_dao.js
  portfolio-project-matching-app/tailwind.config.js
Labels: enhancement

#71 Enhancement `join` and `myProjects`
  portfolio-project-matching-app/backend/dao.js
  portfolio-project-matching-app/backend/daoUser.js
  portfolio-project-matching-app/components/ProjectCard.js
  portfolio-project-matching-app/pages/browseProjects.js
  portfolio-project-matching-app/pages/myProfile.js
  portfolio-project-matching-app/pages/myProjects.js
  portfolio-project-matching-app/pages/test_dao.js
Labels: enhancement

#73 Enhancement-`deleteDocAndAssociations()`
  portfolio-project-matching-app/backend/dao.js
  portfolio-project-matching-app/pages/test_dao.js
Labels: enhancement

#74 Enhancement `dao.js` tidying
  portfolio-project-matching-app/backend/dao.js
  portfolio-project-matching-app/pages/test_dao.js
Labels: enhancement

#72 Enhancement `newProject` integration
  portfolio-project-matching-app/backend/dao.js
  portfolio-project-matching-app/pages/newProject.js
  portfolio-project-matching-app/pages/test_dao.js
Labels: enhancement

#75 Bug `dao.js` closing bracket
  portfolio-project-matching-app/backend/dao.js
Labels: bug

#78 Enhancement design updates
  portfolio-project-matching-app/components/Button.module.css
  portfolio-project-matching-app/components/Input.module.css
  portfolio-project-matching-app/components/Nav.js
  portfolio-project-matching-app/components/Nav.module.css
  portfolio-project-matching-app/components/ProfileForm.js
  portfolio-project-matching-app/components/ProjectCard.js
  portfolio-project-matching-app/components/ProjectCard.module.css
  portfolio-project-matching-app/components/Search.js
  portfolio-project-matching-app/components/Textarea.js
  portfolio-project-matching-app/pages/browseProjects.js
  portfolio-project-matching-app/pages/newProject.js
  portfolio-project-matching-app/pages/project.js
  portfolio-project-matching-app/styles/globals.css
  portfolio-project-matching-app/tailwind.config.js
Labels: enhancement

#77 Enhancement / Bug - `dao.js` `await Promise.all()`
  portfolio-project-matching-app/backend/daoProject.js
  portfolio-project-matching-app/backend/daoUser.js
Labels: bug, enhancement

#76 Feature `myApplications` Page
  portfolio-project-matching-app/backend/dao.js
  portfolio-project-matching-app/backend/daoProject.js
  portfolio-project-matching-app/backend/daoUser.js
  portfolio-project-matching-app/components/ApplicationCard.js
  portfolio-project-matching-app/components/ProjectCard.js
  portfolio-project-matching-app/models/Application.js
  portfolio-project-matching-app/pages/myApplications.js
  portfolio-project-matching-app/pages/myProfile.js
  portfolio-project-matching-app/pages/test_dao.js
Labels: enhancement

#79 Enhancement `myApplications` filtering
  portfolio-project-matching-app/backend/dao.js
  portfolio-project-matching-app/components/ApplicationCard.module.css
  portfolio-project-matching-app/models/Application.js
  portfolio-project-matching-app/models/FilteredApplication.js
  portfolio-project-matching-app/models/FilteredProject.js
  portfolio-project-matching-app/pages/myApplications.js
Labels: enhancement

#80 `Sprint-5` -> `main`
  portfolio-project-matching-app/Firebase/auth.js
  portfolio-project-matching-app/backend/dao.js
  portfolio-project-matching-app/backend/daoProject.js
  portfolio-project-matching-app/backend/daoUser.js
  portfolio-project-matching-app/components/ApplicationCard.js
  portfolio-project-matching-app/components/ApplicationCard.module.css
  portfolio-project-matching-app/components/Button.module.css
  portfolio-project-matching-app/components/Input.module.css
  portfolio-project-matching-app/components/Nav.js
  portfolio-project-matching-app/components/Nav.module.css
  portfolio-project-matching-app/components/NewLogin.js
  portfolio-project-matching-app/components/ProfileForm.js
  portfolio-project-matching-app/components/ProjectCard.js
  portfolio-project-matching-app/components/ProjectCard.module.css
  portfolio-project-matching-app/components/Search.js
  portfolio-project-matching-app/components/Textarea.js
  portfolio-project-matching-app/models/Application.js
  portfolio-project-matching-app/models/FilteredApplication.js
  portfolio-project-matching-app/models/FilteredProject.js
  portfolio-project-matching-app/package-lock.json
  portfolio-project-matching-app/package.json
  portfolio-project-matching-app/pages/browseProjects.js
  portfolio-project-matching-app/pages/myApplications.js
  portfolio-project-matching-app/pages/myProfile.js
  portfolio-project-matching-app/pages/myProjects.js
  portfolio-project-matching-app/pages/newProject.js
  portfolio-project-matching-app/pages/project.js
  portfolio-project-matching-app/pages/signUp.js
  portfolio-project-matching-app/pages/test_dao.js
  portfolio-project-matching-app/styles/globals.css
  portfolio-project-matching-app/tailwind.config.js
Labels: enhancement

#83 Enhancement `dao` cleanup
  portfolio-project-matching-app/Firebase/auth.js
  portfolio-project-matching-app/backend/dao.js
  portfolio-project-matching-app/backend/daoProject.js
  portfolio-project-matching-app/backend/daoTechnology.js
  portfolio-project-matching-app/backend/daoUser.js
  portfolio-project-matching-app/components/ApplicationCard.js
  portfolio-project-matching-app/components/Nav.js
  portfolio-project-matching-app/components/ProjectCard.js
  portfolio-project-matching-app/context/AuthContext.js
  portfolio-project-matching-app/pages/browseProjects.js
  portfolio-project-matching-app/pages/myApplications.js
  portfolio-project-matching-app/pages/myProjects.js
  portfolio-project-matching-app/pages/newProject.js
  portfolio-project-matching-app/pages/project.js
  portfolio-project-matching-app/pages/test_dao.js
Labels: enhancement

#82 Enhancement / Bug - `newProject`
  portfolio-project-matching-app/pages/newProject.js
  portfolio-project-matching-app/pages/test_dao.js
Labels: bug, enhancement

#81 Feature `like` and `dislike` project
  portfolio-project-matching-app/backend/dao.js
  portfolio-project-matching-app/components/ProjectCard.js
  portfolio-project-matching-app/pages/browseProjects.js
Labels: enhancement

#84 Enhancement testing
  portfolio-project-matching-app/__tests__/ApplicationCard.test.js
  portfolio-project-matching-app/__tests__/FilterButtons.test.js
  portfolio-project-matching-app/__tests__/ProjectCard.test.js
  portfolio-project-matching-app/__tests__/browseProjects.test.js
  portfolio-project-matching-app/__tests__/dummy.test.js
  portfolio-project-matching-app/components/ApplicationCard.js
  portfolio-project-matching-app/components/FilterButtons.js
  portfolio-project-matching-app/package-lock.json
  portfolio-project-matching-app/package.json
Labels: enhancement

#85 `Sprint-6` -> `main`
  portfolio-project-matching-app/Firebase/auth.js
  portfolio-project-matching-app/__tests__/ApplicationCard.test.js
  portfolio-project-matching-app/__tests__/FilterButtons.test.js
  portfolio-project-matching-app/__tests__/ProjectCard.test.js
  portfolio-project-matching-app/__tests__/browseProjects.test.js
  portfolio-project-matching-app/__tests__/dummy.test.js
  portfolio-project-matching-app/backend/dao.js
  portfolio-project-matching-app/backend/daoProject.js
  portfolio-project-matching-app/backend/daoTechnology.js
  portfolio-project-matching-app/backend/daoUser.js
  portfolio-project-matching-app/components/ApplicationCard.js
  portfolio-project-matching-app/components/FilterButtons.js
  portfolio-project-matching-app/components/Nav.js
  portfolio-project-matching-app/components/ProjectCard.js
  portfolio-project-matching-app/context/AuthContext.js
  portfolio-project-matching-app/package-lock.json
  portfolio-project-matching-app/package.json
  portfolio-project-matching-app/pages/browseProjects.js
  portfolio-project-matching-app/pages/myApplications.js
  portfolio-project-matching-app/pages/myProjects.js
  portfolio-project-matching-app/pages/newProject.js
  portfolio-project-matching-app/pages/project.js
  portfolio-project-matching-app/pages/test_dao.js
Labels: enhancement

#86 Enhancement Miscellaneous Updates
  portfolio-project-matching-app/.firebase/hosting.b3V0.cache
  portfolio-project-matching-app/Firebase/auth.js
  portfolio-project-matching-app/backend/dao.js
  portfolio-project-matching-app/components/ApplicationCard.js
  portfolio-project-matching-app/components/ProjectCard.js
  portfolio-project-matching-app/pages/myApplications.js
  portfolio-project-matching-app/pages/myProfile.js
  portfolio-project-matching-app/pages/myProjects.js
  portfolio-project-matching-app/pages/test_dao.js
Labels: enhancement

#92 Enhancement `browseProjects` Filter Optimization
  portfolio-project-matching-app/models/Projects.js
  portfolio-project-matching-app/pages/browseProjects.js
Labels: enhancement

#91 Enhancement `myApplications` Filter Optimization
  portfolio-project-matching-app/models/Applications.js
  portfolio-project-matching-app/pages/myApplications.js
Labels: enhancement

#90 Enhancement ProjectCard joinButton
  portfolio-project-matching-app/components/Button.module.css
  portfolio-project-matching-app/components/ProjectCard.js
Labels: enhancement

#97 Enhancement `MultiInputDropDown` Icons
  portfolio-project-matching-app/components/MultipleInputDropdown.js
Labels: enhancement

#96 Enhancement `myProfile` technologies
  portfolio-project-matching-app/backend/dao.js
  portfolio-project-matching-app/components/MultipleInputDropdown.js
  portfolio-project-matching-app/components/ProfileForm.js
Labels: enhancement

#95 Bug `myProfile` buttons
  portfolio-project-matching-app/components/ProjectCard.js
  portfolio-project-matching-app/pages/myProfile.js
Labels: bug

#94 Bug `ProjectCard` Join Button
  portfolio-project-matching-app/components/ProjectCard.js
Labels: bug

#98 Enhancement Improved Color Consistency
  .github/workflows/node.js.yml
  portfolio-project-matching-app/.firebase/hosting.b3V0.cache
  portfolio-project-matching-app/components/ProfileForm.js
  portfolio-project-matching-app/package.json
  portfolio-project-matching-app/pages/signUp.js
Labels: enhancement

#99 `Sprint-7` -> `main`
  .github/workflows/node.js.yml
  portfolio-project-matching-app/.firebase/hosting.b3V0.cache
  portfolio-project-matching-app/Firebase/auth.js
  portfolio-project-matching-app/backend/dao.js
  portfolio-project-matching-app/components/ApplicationCard.js
  portfolio-project-matching-app/components/Button.module.css
  portfolio-project-matching-app/components/MultipleInputDropdown.js
  portfolio-project-matching-app/components/ProfileForm.js
  portfolio-project-matching-app/components/ProjectCard.js
  portfolio-project-matching-app/models/Applications.js
  portfolio-project-matching-app/models/Projects.js
  portfolio-project-matching-app/package.json
  portfolio-project-matching-app/pages/browseProjects.js
  portfolio-project-matching-app/pages/myApplications.js
  portfolio-project-matching-app/pages/myProfile.js
  portfolio-project-matching-app/pages/myProjects.js
  portfolio-project-matching-app/pages/signUp.js
  portfolio-project-matching-app/pages/test_dao.js
Labels: enhancement
